### ISSUE TITLE
Boosts sent from BoostCLI are incorrectly base64 encoded

### ISSUE THREAD

**Issue by charabaruk** [valcanobacon/BoostCLI#4]
See [thread on PodcastIndex.social](https://podcastindex.social/web/@coldacid/107718755448615670) but the long and short of it is that it appears that the value for custom record 7629169 is being base64 encoded when it shouldn't be. This causes boostagrams sent with BoostCLI to go missing, which is a big problem with shared node services like Satoshis.Stream where the podcast information in the custom record is required to determine which users should receive the boost value.

**Comment by valcanobacon** [comment]
Thanks for pointing this out. I have seen those custom key/value properties in some value blocks but was not sure what they were. It would be a pretty simple fix. Let me see what I can do.

**Comment by valcanobacon** [comment]
I think the encoding of 7629169 is correct but I will double check. I thought its because I am not including customKey/customValue in the custom records of the transactions ```<podcast:valueRecipient name="Dreb Scott (Chapters)" type="node" address="033868c219bdb51a33560d854d500fe7d3898a1ad9e05dd89d0007e11313588500" split="5" customKey="112111100" customValue="wal_j39hpWOkxCDUYg"/>```

**Comment by charabaruk** [comment]
Going through my own payments and invoices exported from RTL, the ones done via lncli and the ones received from various apps that I have seen showing up in Helipad are all singly base64-encoded in the CSV files, but the payments sent with BoostCLI are all double base64-encoded.

I believe also that the feed URL and PI feed ID should also be included if present; I notice that is what Fountain does at the very least. Also, value_msat_total seems to be missing for boosts sent from BoostCLI, which should definitely be present for boosts with multiple recipients (although that is probably a separate issue).

**Comment by charabaruk** [comment]
Regarding `customKey` and `customValue` in the valueRecipient tag, there doesn't appear to be anything matching those in [bLIP-10](https://github.com/lightning/blips/blob/master/blip-0010.md). Per the [value ref](https://github.com/Podcastindex-org/podcast-namespace/blob/main/value/value.md) this should be used as custom record data in a payment (equivalent to ``--data $customKey=`echo $customValue |  od -A n -t x1 | sed 's/ *//g' | tr -d '\n'` `` on the lncli command line).

**Comment by valcanobacon** [comment]
@coldacid I think I fixed everything you mentioned. thanks for testing all that. Let me know if you see any more problems.

**Comment by valcanobacon** [comment]
I just tested with LNPay which requires a custom key/value and BoostCLI worked. I don't want to give Telegram my Phone number which makes it difficult to test satoshis.stream but pretty sure its working.

**Comment by charabaruk** [comment]
@valcanobacon I'm still waiting to hear Spencer if the test I sent to him worked or not, but so far it looks like it should.

**Comment by charabaruk** [comment]
@valcanobacon and it looks like it worked!
